name: Build and push Backend Docker image to Gitlab registry

on:
  push:
    tags:
      - v*

jobs:
  push-image:
    runs-on: ubuntu-latest
    name: Build and push ${{ github.repository }} [backend] to GitLab repository
    steps:
      - name: Login to GitLab
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.gitlab.com/kosbalint/ajandekutalvany/${{ github.event.repository.name }}/backend
          flavor: |
            latest=false

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          registry: registry.gitlab.com
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}